services:
  backend:
    image: golang:1.22.5-bookworm
    ports:
      - 8080:8080
    command: go run main.go
    volumes:
      - ./backend:/go/
    depends_on:
      - database

  frontend:
    image: node:latest
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./frontend/react-arqui:/home/node/app
    working_dir: /home/node/app

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - 3306:3306
    volumes:
      - ./.database:/var/lib/mysql
      - ./arq-soft:/docker-entrypoint-initdb.d